spring.application.name=smart-healthcare-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_healthcare
spring.datasource.username=admin
spring.datasource.password=6789998212

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.signerKey=7e9d3eefed86050adee9236b5729f983dd42754ee9d60f6e110fcd362d4fb3604fdd06d6ba1b2754e8273a124906686ea67035bad86dd0a1dd64355a62265d74
