spring.application.name=medical-appointment-system

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.signerKey=${JWT_SIGNER_KEY}

springdoc.packagesToScan=com.healthcare.api.controller